// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.1
// source: level.proto

package level

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PropertyInt_PropertyIntType int32

const (
	PropertyInt_int PropertyInt_PropertyIntType = 0
)

// Enum value maps for PropertyInt_PropertyIntType.
var (
	PropertyInt_PropertyIntType_name = map[int32]string{
		0: "int",
	}
	PropertyInt_PropertyIntType_value = map[string]int32{
		"int": 0,
	}
)

func (x PropertyInt_PropertyIntType) Enum() *PropertyInt_PropertyIntType {
	p := new(PropertyInt_PropertyIntType)
	*p = x
	return p
}

func (x PropertyInt_PropertyIntType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyInt_PropertyIntType) Descriptor() protoreflect.EnumDescriptor {
	return file_level_proto_enumTypes[0].Descriptor()
}

func (PropertyInt_PropertyIntType) Type() protoreflect.EnumType {
	return &file_level_proto_enumTypes[0]
}

func (x PropertyInt_PropertyIntType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyInt_PropertyIntType.Descriptor instead.
func (PropertyInt_PropertyIntType) EnumDescriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{0, 0}
}

type PropertyString_PropertyStringType int32

const (
	PropertyString_string PropertyString_PropertyStringType = 0
)

// Enum value maps for PropertyString_PropertyStringType.
var (
	PropertyString_PropertyStringType_name = map[int32]string{
		0: "string",
	}
	PropertyString_PropertyStringType_value = map[string]int32{
		"string": 0,
	}
)

func (x PropertyString_PropertyStringType) Enum() *PropertyString_PropertyStringType {
	p := new(PropertyString_PropertyStringType)
	*p = x
	return p
}

func (x PropertyString_PropertyStringType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropertyString_PropertyStringType) Descriptor() protoreflect.EnumDescriptor {
	return file_level_proto_enumTypes[1].Descriptor()
}

func (PropertyString_PropertyStringType) Type() protoreflect.EnumType {
	return &file_level_proto_enumTypes[1]
}

func (x PropertyString_PropertyStringType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropertyString_PropertyStringType.Descriptor instead.
func (PropertyString_PropertyStringType) EnumDescriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{1, 0}
}

type PropertyInt struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string                      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  PropertyInt_PropertyIntType `protobuf:"varint,2,opt,name=type,proto3,enum=jumper.levels.PropertyInt_PropertyIntType" json:"type,omitempty"`
	Value int32                       `protobuf:"varint,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PropertyInt) Reset() {
	*x = PropertyInt{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropertyInt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyInt) ProtoMessage() {}

func (x *PropertyInt) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyInt.ProtoReflect.Descriptor instead.
func (*PropertyInt) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{0}
}

func (x *PropertyInt) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyInt) GetType() PropertyInt_PropertyIntType {
	if x != nil {
		return x.Type
	}
	return PropertyInt_int
}

func (x *PropertyInt) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

type PropertyString struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string                            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type  PropertyString_PropertyStringType `protobuf:"varint,2,opt,name=type,proto3,enum=jumper.levels.PropertyString_PropertyStringType" json:"type,omitempty"`
	Value string                            `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *PropertyString) Reset() {
	*x = PropertyString{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PropertyString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropertyString) ProtoMessage() {}

func (x *PropertyString) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropertyString.ProtoReflect.Descriptor instead.
func (*PropertyString) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{1}
}

func (x *PropertyString) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PropertyString) GetType() PropertyString_PropertyStringType {
	if x != nil {
		return x.Type
	}
	return PropertyString_string
}

func (x *PropertyString) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_level_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_level_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_level_proto_rawDescGZIP(), []int{2}
}

func (x *Point) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_level_proto protoreflect.FileDescriptor

var file_level_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x6a,
	0x75, 0x6d, 0x70, 0x65, 0x72, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x22, 0x93, 0x01, 0x0a,
	0x0b, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x3e, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2a,
	0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x65, 0x72, 0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x49, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65,
	0x72, 0x74, 0x79, 0x49, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x1a, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x49, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x07, 0x0a, 0x03, 0x69, 0x6e, 0x74,
	0x10, 0x00, 0x22, 0xa2, 0x01, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x44, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x30, 0x2e, 0x6a, 0x75, 0x6d, 0x70, 0x65, 0x72,
	0x2e, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79,
	0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x20, 0x0a, 0x12, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74,
	0x79, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x73,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x10, 0x00, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e, 0x74,
	0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x78, 0x12, 0x0c,
	0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01, 0x79, 0x42, 0x10, 0x5a, 0x0e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_level_proto_rawDescOnce sync.Once
	file_level_proto_rawDescData = file_level_proto_rawDesc
)

func file_level_proto_rawDescGZIP() []byte {
	file_level_proto_rawDescOnce.Do(func() {
		file_level_proto_rawDescData = protoimpl.X.CompressGZIP(file_level_proto_rawDescData)
	})
	return file_level_proto_rawDescData
}

var file_level_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_level_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_level_proto_goTypes = []interface{}{
	(PropertyInt_PropertyIntType)(0),       // 0: jumper.levels.PropertyInt.PropertyIntType
	(PropertyString_PropertyStringType)(0), // 1: jumper.levels.PropertyString.PropertyStringType
	(*PropertyInt)(nil),                    // 2: jumper.levels.PropertyInt
	(*PropertyString)(nil),                 // 3: jumper.levels.PropertyString
	(*Point)(nil),                          // 4: jumper.levels.Point
}
var file_level_proto_depIdxs = []int32{
	0, // 0: jumper.levels.PropertyInt.type:type_name -> jumper.levels.PropertyInt.PropertyIntType
	1, // 1: jumper.levels.PropertyString.type:type_name -> jumper.levels.PropertyString.PropertyStringType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_level_proto_init() }
func file_level_proto_init() {
	if File_level_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_level_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropertyInt); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PropertyString); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_level_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_level_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_level_proto_goTypes,
		DependencyIndexes: file_level_proto_depIdxs,
		EnumInfos:         file_level_proto_enumTypes,
		MessageInfos:      file_level_proto_msgTypes,
	}.Build()
	File_level_proto = out.File
	file_level_proto_rawDesc = nil
	file_level_proto_goTypes = nil
	file_level_proto_depIdxs = nil
}
